@NLADotNetInternshipTraining.BusTicketBookingSystem_HostAddress = http://localhost:5014

GET {{NLADotNetInternshipTraining.BusTicketBookingSystem_HostAddress}}/weatherforecast/
Accept: application/json

###
